#! /usr/bin/env python3
#
# muesli-test
#
# This file is part of MUESLI.
#
# Copyright (C) 2011, Ansgar Burchard <ansgar (at) 43-1.org>
# Copyright (C) 2011, Matthias Kuemmerer <matthias (at) matthias-k.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import subprocess
import sys
import time
import traceback

os.environ['PYRAMID_DEBUG_TEMPLATES'] = '1'
while True:
    try:
        start = time.time()
        subprocess.Popen(['./muesli-serve', '--reload']).communicate()
        end = time.time()
        if end - start < 2:
            # Don't start endless loop on syntax errors
            sys.exit()
    except Exception as e:
        print(traceback.print_exc())
        print("Terminating...")
        sys.exit()
