#! /usr/bin/env python3
#
# muesli-serve
#
# This file is part of MUESLI.
#
# Copyright (C) 2011, Ansgar Burchard <ansgar (at) 43-1.org>
# Copyright (C) 2011, Matthias Kuemmerer <matthias (at) matthias-k.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import subprocess
import sys

from waitress import serve

import muesli.web

if '--reload' in sys.argv:
    files = subprocess.Popen(['find', '.', '-iname', '*.pt'],
                             stdout=subprocess.PIPE).communicate()[0].decode('utf-8').split('\n')[:-1]
    import paste.reloader

    for template_file in files:
        paste.reloader.watch_file(template_file)
    paste.reloader.install()

app = muesli.web.main()
serve(app, host=muesli.config['listen']['host'], port=muesli.config['listen']['port'], trusted_proxy='*',
      trusted_proxy_headers="x-forwarded-for x-forwarded-host x-forwarded-proto x-forwarded-port")
