"""Description for Bearer Token

Revision ID: 3fa858c7369d
Revises: ba59ed32d836
Create Date: 2018-11-30 15:38:22.554107

"""

# revision identifiers, used by Alembic.
revision = '3fa858c7369d'
down_revision = 'ba59ed32d836'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bearertokens', sa.Column('description', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'clients', ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('bearertokens', 'description')
    # ### end Alembic commands ###
