"""Description for Bearer Token

Revision ID: 3fa858c7369d
Revises: ba59ed32d836
Create Date: 2018-11-30 15:38:22.554107

"""

# revision identifiers, used by Alembic.
revision = '3fa858c7369d'
down_revision = 'ba59ed32d836'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beaker_cache')
    op.add_column('bearertokens', sa.Column('description', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'clients', ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('bearertokens', 'description')
    op.create_table('beaker_cache',
    sa.Column('namespace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('namespace', name='beaker_cache_pkey')
    )
    # ### end Alembic commands ###
