"""BearerToken

Revision ID: 8c2d5633e0d2
Revises: 3d0645977378
Create Date: 2019-01-04 20:24:35.734810

"""

# revision identifiers, used by Alembic.
revision = '8c2d5633e0d2'
down_revision = '3d0645977378'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bearertokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('access_token', sa.String(length=100), nullable=True),
    sa.Column('refresh_token', sa.String(length=100), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bearertokens')
    # ### end Alembic commands ###
