"""email_preferences

Revision ID: caab371ebc9f
Revises:3d0645977378
Create Date: 2019-02-14 11:20:48.396180

"""

# revision identifiers, used by Alembic
revision = 'caab371ebc9f'
down_revision = '3d0645977378'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'email_preferences',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('lecture_id', sa.Integer(), nullable=False),
        sa.Column('receive_status_mails', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'lecture_id'),
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_preferences')
# ### end Alembic commands ###
