# -*- coding: utf-8 -*-
#
# muesli/web/viewsApi.py
#
# This file is part of MUESLI.
#
# Copyright (C) 2018, Philipp Göldner  <pgoeldner (at) stud.uni-heidelberg.de>
#                     Christian Heusel <christian (at) heusel.eu>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
from os import path, stat
from ast import literal_eval
import requests

STATIC_HEADERS = {'Accept': 'application/json'}
MUESLI_URL = "http://localhost:8080"


def authenticate(username, password, header_name="") -> dict:
    """TODO: Docstring for function.

    :arg1: TODO
    :returns: TODO

    """
    if not header_name:
        header_name = username
    if path.isfile(header_name) and stat(header_name).st_size != 0:
        with open(header_name, 'r') as header:
            header_content = literal_eval(header.read())
            print('Read header from "{}"!'.format(header_name))
            return header_content
    else:
        with open(header_name, 'w') as header:
            r = requests.post(
                MUESLI_URL+'/api/v1/login',
                data={"email": username, "password": password}
            )
            token = r.json().get("token", "")
            print(r.json())
            header_content = {'Authorization': 'Bearer '+token}
            header_content.update(STATIC_HEADERS)
            header.write("# This file was generated by: {}!\n".format(__file__))
            header.write(json.dumps(header_content))
            print('Created {}!'.format(header_name))
            return header_content

def get(endpoint, header):
    endpoint = MUESLI_URL + endpoint
    r = requests.get(endpoint, headers=header)
    print(r.json())

def put(endpoint, header):
    endpoint = MUESLI_URL + endpoint
    lecture = '{"term": 20181, "name": "Irgendwas", "lecturer": "Ich auch"}'
    r = requests.get(endpoint, lecture, headers=header)
    print(r.json())

def main():
    headers = authenticate('admin@muesli.org', 'adminpassword')
    # headers = authenticate('test@test.de', '1234')
    endpoint = "/api/v1/whoami"
    get(endpoint, headers)


if __name__ == "__main__":
    main()
